
# define file location
REF_GENOME = "/staging/leuven/stg_00079/teaching/hg38_9/chr9.fa"
SNPEFF_JAR = "/lustre1/project/stg_00079/teaching/I0U19a_conda_2026/share/snpeff-5.4.0a-0/snpEff.jar"

# tell snakemake what is the ultimate goal
rule all:
  input:
    "010.fastqc/TLE66_T_fastqc.html",
    "010.fastqc/TLE66_N_fastqc.html",
    "100.final/snps.annotated.tsv"

# rule to generate fastqc html
rule fastqc:
  input:
    "{sample}.fastq"
  output:
    html="010.fastqc/{sample}_fastqc.html", #define naming html for easier access
    zip="010.fastqc/{sample}_fastqc.zip" 
  log:
    "010.fastqc/{sample}.log" #output log per sample
  shell:
    """
    set -euo pipefail
    mkdir -p 010.fastqc
    fastqc {input} -o 010.fastqc > {log} 2>&1

    #check if output not empty
    [ -s {output.html} ] || {{ echo "Error: fastqc html is empty!"; exit 1; }}
    """

rule bwa_map:
  input:
    fq="{sample}.fastq", #define so later on we can define as input.fq
    ref=REF_GENOME
  output:
    sam="020.bam/{sample}.sam"
  shell:
    """
    set -euo pipefail
    mkdir -p 020.bam
    bwa mem {input.ref} {input.fq} > {output.sam}

    [ -s {output.sam} ] || {{ echo "Error: bam output is empty!"; exit 1; }}
    """

rule sort_bam:
  input:
    sam="020.bam/{sample}.sam"
  output:
    bam="020.bam/{sample}.bam"
  shell:
    """
    set -euo pipefail
    samtools sort -o {output.bam} {input.sam}

    [ -s {output.bam} ] || {{ echo "Error: BAM output is empty!"; exit 1; }}

    """

  

rule index_bam:
  input:
    "020.bam/{sample}.bam"
  output:
    "020.bam/{sample}.bam.bai"
  shell:
    """
    set -euo pipefail
    samtools index {input} {output}
    [ -s {output} ] || {{ echo "Error: BAM index is empty!"; exit 1; }}
    """

rule variant_calling:
  input:
    bam_t = "020.bam/TLE66_T.bam",  
    bam_n = "020.bam/TLE66_N.bam",
    bai_t = "020.bam/TLE66_T.bam.bai",
    bai_n = "020.bam/TLE66_N.bam.bai",
    ref=REF_GENOME
  output:
    "030.vcf/raw_snps.vcf"
  shell:
    """
    set -euo pipefail
    mkdir -p 030.vcf/
    bcftools mpileup -f {input.ref} {input.bam_t} {input.bam_n} | bcftools call -mv -Ov -o {output}

    [ -s {output} ] || {{ echo "Error: raw_snps.vcf is empty!"; exit 1; }}

    """

rule clean_variants:
  input:
    raw="030.vcf/raw_snps.vcf",
    ref=REF_GENOME
  output:
    "030.vcf/clean_snps.vcf"
  shell:
    """
    set -euo pipefail
    cat {input.raw} \
    | vt decompose - \
    | vt normalize -n -r {input.ref} - \
    | vt uniq - \
    | vt view -f "QUAL>20" -h - \
    > {output}

    [ -s {output} ] || {{ echo "Error: clean_snps.vcf is empty!"; exit 1; }}
    """

rule annotate_variants:
  input:
    "030.vcf/clean_snps.vcf"
  output:
    vcf="030.vcf/annotated_snps.vcf",
    stats="030.vcf/snpEff_summary.html"
  resources:
    mem_mb=2000
  shell:
    """
    set -euo pipefail
    java -Xmx3400m -jar {SNPEFF_JAR} eff hg38 \
        -dataDir /staging/leuven/stg_00079/teaching/snpeff_db \
        -stats {output.stats} \
        {input} > {output.vcf}

    [ -s {output.vcf} ] || {{ echo "Error: annotated_snps.vcf is empty!"; exit 1; }}
    """

rule extract_tsv:
  input:
    "030.vcf/annotated_snps.vcf"
  output:
    "100.final/snps.annotated.tsv"
  shell:
    """
    set -euo pipefail
    mkdir -p 100.final/

    python extract_vcf.py {input} {output}

    [ -s {output} ] || {{ echo "Error: snps.annotated.tsv is empty!"; exit 1; }}
    """
